management:
  endpoints:
    web:
      exposure:
        include: '*'
#  endpoint:
#    health:
#      group:
#        readiness:
#          include:
#            - readinessProbe
#            - db
server:
  shutdown:
    grace-period: 30s
wavefront:
  application:
    name: sv-k8s
    service: kloud-native
