management:
  endpoints:
    web:
      exposure:
        include: '*'
#  endpoint:
#    health:
#      group:
#        readiness:
#          include:
#            - readinessProbe
#            - db
server:
  shutdown:
    grace-period: 30s
