---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
  labels:
    app: "kloudnative"
    kind: "k8s-native"
    version: "1.0.M1"
    group: "humourmind"
  name: "kloudnative"
spec:
  ports:
  - name: "web"
    port: 8080
    targetPort: 8080
  selector:
    app: "kloudnative"
    kind: "k8s-native"
    version: "1.0.M1"
    group: "humourmind"
  type: "ClusterIP"
