apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: kloudnative
      context: ../
      buildpack:
        builder: humourmind/paketo-java-builder-tiny@sha256:40be20ed070cce98f6cfa3b9b588919502cc5f4f7ee330d19ec28cddf7d985bb
        forcePull: false
#        runImage: humourmind/cnb-run:tiny
  tagPolicy:
    envTemplate:
      template: 'docker.io/humourmind/{{.IMAGE_NAME}}:1.0.M1'
  local:
    push: true
deploy:
  kustomize: {}
